version: '3.3'
services:
  postgresql:
    build: .
    image: ragedunicorn/postgresql:1.0.2-stable
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  postgresql_data: {}
