version: '3.3'
services:
  postgresql:
    image: ragedunicorn/postgresql:1.0.2-stable
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    secrets:
      - com.ragedunicorn.postgresql.app_user
      - com.ragedunicorn.postgresql.app_user_password
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  postgresql_data: {}
secrets:
  com.ragedunicorn.postgresql.app_user:
    external: true
  com.ragedunicorn.postgresql.app_user_password:
    external: true
