version: '3.7'
services:
  postgresql:
    build: .
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  postgresql_data: {}
