version: '3.8'
services:
  container-test:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable", "--config", "/test/postgresql_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-test-metadata:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable", "--config", "/test/postgresql_metadata_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-test-command:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-stable", "--config", "/test/postgresql_command_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-dev-test:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev", "--config", "/test/postgresql_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-dev-test-metadata:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev", "--config", "/test/postgresql_metadata_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
  container-dev-test-command:
    image: ragedunicorn/container-test:${CONTAINER_STRUCTURE_TEST_VERSION}-stable
    volumes:
        - ./test/:/test
        - /var/run/docker.sock:/var/run/docker.sock
    command: ["--image", "ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev", "--config", "/test/postgresql_command_test.yml"]
    labels:
      com.ragedunicorn.container-test.environment: "test"
      com.ragedunicorn.container-test.description: "Google Container Structure Test"
