version: '3.7'
services:
  postgresql:
    image: ragedunicorn/postgresql:1.1.0-stable
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    secrets:
      - com.ragedunicorn.postgresql.app_user
      - com.ragedunicorn.postgresql.app_user_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  postgresql_data: {}
secrets:
  com.ragedunicorn.postgresql.app_user:
    external: true
  com.ragedunicorn.postgresql.app_user_password:
    external: true
